name: R Lint (disabled by default)
on: [workflow_dispatch]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
      - name: Install lintr
        run: Rscript -e "install.packages('lintr')"
      - name: Lint
        run: Rscript -e "lintr::lint_dir()"
